export const OurAdvisorsData = [
  {
    id: 1,
    name: "Moerieda Mackay",
    lastName: "Mackay",
    position: "Founder & CEO of Stride",
    image: "/images/advisors/advisor1.png",
    about: {
      name: "Moerieda Mackay",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 2,
    name: "Ali Hussein Kassim",
    lastName: "Kassim",
    position: "Chairman, Association of Fintechs, Kenya",
    image: "/images/advisors/advisor2.png",
    about: {
      name: "Ali Hussein Kassim",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 3,
    name: "Alakanani Itireleng",
    lastName: "Itireleng",
    position: "CEO, Satoshicentre",
    image: "/images/advisors/advisor3.png",
    about: {
      name: "Alakanani Itireleng",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 4,
    name: "Raj A. Kapoor",
    lastName: "Kapoor",
    position: "Founder/CEO India Blockchain Alliance",
    image: "/images/advisors/advisor3.png",
    about: {
      name: "Raj A. Kapoor",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 5,
    name: "Christian Duffus",
    lastName: "Duffus",
    position: "Founder & CEO Fonbnk",
    image: "/images/advisors/advisor1.png",
    about: {
      name: "Christian Duffus",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 6,
    name: "Kue Barinor Paul",
    lastName: "Paul",
    position: "Principal Partner, Blocklex.Tech",
    image: "/images/advisors/advisor2.png",
    about: {
      name: "Kue Barinor Paul",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 7,
    name: "Kue Barinor Paul",
    lastName: "Paul",
    position: "Principal Partner, Blocklex.Tech",
    image: "/images/advisors/advisor3.png",
    about: {
      name: "Kue Barinor Paul",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
  {
    id: 8,
    name: "Kue Barinor Paul",
    lastName: "Paul",
    position: "Principal Partner, Blocklex.Tech",
    image: "/images/advisors/advisor3.png",
    about: {
      name: "Kue Barinor Paul",
      title: "Pioneer Member of The Blockchain Research Institute",
      body: "Kogi salvia cillum selvage small batch aliquip seitan DSA bitters. Ad chambray occaecat poutine esse humblebrag XOXO authentic hot chicken.",
    },
  },
];
